---
- name: Deploy Kubernetes Resources
  hosts: localhost
  become: false

  tasks:
    - name: Include MySQL tasks
      include_tasks: roles/deploy_files/aux/get-ip.yml

    - name: Include MySQL tasks
      include_tasks: roles/deploy_files/mysql/mysql-deploy.yml

    - name: Retrieve pod names
      include_tasks: roles/deploy_files/aux/get-pod.yml

    - name: Notify App Deploy
      include_tasks: roles/deploy_files/aux/wait-mysql-deploy.yml

    - name: Notify Laravel Deploy
      include_tasks: roles/deploy_files/app/laravel-deploy.yml
