- name: Delete MySQL service
  command: kubectl delete -f roles/deploy_files/mysql/mysql-service.yml
  ignore_errors: true

- name: Delete MySQL deployment
  command: kubectl delete -f roles/deploy_files/mysql/mysql-deployment.yml
  ignore_errors: true

- name: Delete MySQL PVC
  command: kubectl delete -f roles/deploy_files/mysql/mysql-pvc.yml
  ignore_errors: true
  when: "{{ delete_data }}"
