version: "3.4"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
            - "1400:1433"

        environment:
            MSSQL_SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"