apiVersion: v1
kind: Service
metadata:
  name: laravelio-service
  labels:
    app: laravelio
    tier: application
spec:
  type: NodePort
  selector:
    app: laravelio
  ports:
    - targetPort: 8000  # Port that containers are listening on
      port: 8000        # Port number exposed internally in the cluster
      nodePort: 30007   # Port exposed to the outside
  sessionAffinity: ClientIP
