- name: Apply Laravel deployment
  command: kubectl apply -f roles/deploy_files/app/laravel-deployment.yml

- name: Create processed laravel-deployment-seed file
  template:
    src: roles/deploy_files/app/laravel-deployment-seed.yml
    dest: /tmp/laravel-deployment-seed-processed.yml

- name: Apply Laravel deployment seed
  command: kubectl apply -f /tmp/laravel-deployment-seed-processed.yml

- name: Remove processed laravel-deployment-seed file
  file:
    path: /tmp/laravel-deployment-seed-processed.yml
    state: absent

- name: Apply Laravel service
  command: kubectl apply -f roles/deploy_files/app/laravel-service.yml