- name: Wait until MySQL server is ready
  command: kubectl exec -it "{{ mysql_pod_name }}" -- mysqladmin --host=0.0.0.0 --user=myuser --password="password" status
  register: mysql_status
  until: mysql_status.stdout_lines | regex_search('Uptime')
  retries: 10
  delay: 20

- name: Trigger handler when MySQL server is ready
  debug:
    msg: "MySQL server is ready, activating handler"
  when: mysql_status.stdout_lines | regex_search('Uptime')
